---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: loadbalancerpool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.20.136-10.10.20.145
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - loadbalancerpool
