---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      interval: 12h
      version: '34.3.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  targetNamespace: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: [web, websecure]
        matchRule: Host(`traefik-dashboard.talos.local.sandrolab.net`)
        # middlewares:
        # - name: traefik-auth-middleware
        tls:
          secretName: traefik-dashboard-certificate-secret
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true