---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAjY1zJ1qzw8OdiXFIQ3auK/JQRUKbsRiwJrhFtP4e0uWa7LoHIP9q1m2GnTRaVJRLhhs5oi9E3k7Hh4YkKLWV5eHhfTElSd7NAodyNcjpyFKjCKCleF+gg1jR193MwOqACqS90K5aOp3ARYKfuj+kU8strb6CQ6HbVST+5iHBYnsikS4tOfVsBmSw7G3hpBLy+53QGQO5qZHgot/SI9eBlJ0VILtkRr52VosSDQId+c09Iy7rgBdO+EccjXmV367STLQfTCaHPOvTToSJB9ovHy9sz0zDIdBgowHwa7HOA5eVRH3reF3WFUqVD7RSj7JWqDqepm2r88eRKNnNU28KwNWy5dM/Ym5p/xueZHC3pu+OrcfYvxAvw74sllgqkv/4wYJ/uFkJp0UxCU7FtTBDpltMZNDkv9ggVpUcA3umn/lKUgZWoNvUaEA9wAIKkMDipycUj0S1irvGdw9MNTmzbVL/KQqcX2yS5CiMTC/0SZy09lQaJeUlMkV5odPevQa8eKhiXNqFwof+faJb8voZX+cjmjZG2w6eoyDz4bXAtvH74loW1DYuoDnFuN8OuTturiUQmr06ARys3IZH705xweBSu8E2YktGyfaIpQ0K/4cgblMNSGt4PKTZizYhGsmvSb++nxLnaWCYx9PGV1oJ/XuxiMsSmND0FLmaENK7gwvr/snaTTSUhBadmsRizmElL0jHIOIErJcG19WxdOvngAzykkoUvOh4gbUJ6tjUzU4EFRGypyBcN
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: sandro.joost@hotmail.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token