---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgB10utyzAnbPyI9KJom5LPcIcKLrcHL+jPNySTUphsxQNNM9G4Tylz04tSKs0dqTLTAaPmYZZ6Jm9JwRdzWvyPL2zdRCoA66D6XaTvaqP17+dOdCEe4BnKbMmpuWmwOCC54tSTQSyBGpwPyBPiiNkvkbLwCKKbfxqyYqJJs6TVnzNdc3M4QtantyZni7Op1ZscEX1c8+24iFo/zYzE0yaP9sdGAUoPb6aNzyFLLY8Innz9ZpbmhOUuwt3s5LeN3cog3E4Nt7q9EqcPD+N6SAS87fePLQIXmKXdw30TPRGNaZoSkdTn76/u2r5PHASq19OdIfv8Wx/R0AMhGt0/Emt6wh1XVsiOvxyYcKlvnhLkZl1oKxuF576H7JzdxSzmCVoel0w1PGvTIDaNnQZzRfOh5nHI6wKUJeP/aBs42DpeUw95kxbW1W/RE1aM9PV4isqF1uOKHHg1n+/GquCcGQ3OWhz3ZdWkLUhO6SsKNiKyJLgqJrGfm1SiCdNF0idEMlLO1HkpcT2UME2vZwqE8EivM3Pf2sX7fNbbjr6Y9X7grEKBYXOVvNmxvNx82WpZBgdDvl4atRC1gIt4S3osniXZsk6I3FH42rHqamQ3TWE/l5v3bfqpCtZ3Rolwcgr0rCJTb3x3aHQEtpyNO8wqA8c7MP21nqFPoS6RCTt6aAemcU61I8AucC+Wk9FTiNIyC1M++ZelMRojp+vqiNxI5+yI9YdPv1en4nkCryCVXs9GzB4LsI6RRCnCCDLGSkwj0/9u5TPtY2mtjliSXWKNu4cTFLbK9FXbputztzutjSAcYipcliFak0g8tmFW4JoM=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-secret
      namespace: renovate
