name: Test Definitions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Make script runnable
        run: chmod +x ./scripts/validate.sh
      - name: Validate manifests
        run: ./scripts/validate.sh